# Generated by Django 5.0.4 on 2024-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('note', models.IntegerField()),
                ('avis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
