# Generated by Django 5.0.4 on 2024-05-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysapp', '0002_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='continent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paysapp.continent'),
        ),
    ]
